#!/bin/bash

## \brief SCRIPT
## \require coreutils

include core/shellman.sh

[ $# -eq 0 ] && usage

main() {
  case $1 in
    ## \option -h, --help
    ## Prints this help and exit.
    -h|--help) shellman "$0"; exit 0 ;;
  esac
}

## \usage SCRIPT
main "$@"
