before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y shellcheck devscripts zsh
install:
  - printf "3\n2\n" | ./install.sh
  - export shellm="$(pwd)"
  - . "${shellm}/usr/shellmrc"
script:
  - ./test.sh -C
  - ./test.sh -C -u
