#!/bin/bash

READLINK=$(which readlink)
DIRNAME=$(which dirname)
RM=$(which rm)
LN=$(which ln)
MORE=$(which more)

SCRIPT_LOCATION=${BASH_SOURCE[0]}
if [ -x "${READLINK}" ]; then
  while [ -L "${SCRIPT_LOCATION}" ]; do
    SCRIPT_LOCATION=$("${READLINK}" -e "${SCRIPT_LOCATION}")
  done
fi
PARENT_DIR="$(cd "$("${DIRNAME}" "${SCRIPT_LOCATION}")" && pwd)"

run_shellm() {
  export shellm="${PARENT_DIR}"
  (
    exec bash -i 4<<SCRIPT 5<&0 <&4
. "$shellm/usr/shellmrc"
# You are now in an interactive shell with shellm loaded.
# Use some commands and stuff
exec 4>&- <&5
SCRIPT
  )
}

discover() {
    echo "TODO: welcome, here is what you can do, etc."
}

main() {
  while [ $# -ne 0 ]; do
    case $1 in
      --discover) discover ;;
    esac
  done
  run_shellm
}

main "$@"
