.if n.ad l
.nh
.TH find.sh 1 "" "Shellman 0.2.1" "User Commands"
.SH "FUNCTIONS"
find_script [NAME]
.br
find_lib <NAME>
.br
find NAME
.br
.IP "\fBfind_script [NAME]\fR" 4
Find a script.

.IP "\fBfind_lib <NAME>\fR" 4
Find a library file.

.IP "\fBfind NAME\fR" 4
Find either a script or a library file.

