.if n.ad l
.nh
.TH require.sh 1 "" "Shellman 0.2.1" "User Commands"
.SH "FUNCTIONS"
list_requirements [script]
.br
list_missing_requirements [script]
.br
.IP "\fBlist_requirements [script]\fR" 4
Recursively list the requirements of a script.

.IP "\fBlist_missing_requirements [script]\fR" 4
Recursively list the missing requirements of a script.

