#!/usr/bin/env bash

if [ -d "${BASHER_PACKAGES_PATH}" ]; then
  PATH="${BASHER_PACKAGES_PATH}/shellm/core/libexec:${PATH}"
else
  PATH="$(basher package-path shellm/core/libexec):${PATH}"
fi

export PATH

command="$1"

case ${command} in
  "") shellm-help ;;
  *)
    command_path="$(command -v "shellm-${command}" || true)"
    if [ -z "${command_path}" ]; then
      echo "shellm: no such command '${command}'" >&2
      exit 1
    fi

    shift 1
    "${command_path}" "$@"
  ;;
esac
