.if n.ad l
.nh
.TH new 1 "" "Shellman 0.2.1" "User Commands"
.SH "NAME"
new \- creates a new script in your shellm/usr/bin directory
.SH "SYNOPSIS"
.br
\fBnew\fR new \fIFILENAME\fR [\fITEMPLATE\fR] | \fB\-h\fR
.SH "DESCRIPTION"
This script creates a new file in your shellm/usr/bin directory,
makes it executable, writes some lines in it, like the shebang
#!/bin/bash, documentation lines and others, then
opens it for you to write the rest of the code.

.SH "OPTIONS"
.IP "\fB-h\fR,\fB --help\fR" 4
Prints this help and exit
