.if n.ad l
.nh
.TH shellm-mod 1 "" "Shellman 0.2.1" "User Commands"
.SH "NAME"
shellm-mod \- open a file in shellm/bin or shellm/lib
.SH "SYNOPSIS"
.br
\fBshellm-mod\fR shellm\fB\-mod\fR \fIFILENAME\fR [\fIEDITOR\fR] | \fB\-h\fR
.SH "OPTIONS"
.IP "\fB-h\fR,\fB --help\fR" 4
Prints this help and exit
