.if n.ad l
.nh
.TH shellm-del 1 "" "Shellman 0.2.1" "User Commands"
.SH "NAME"
shellm-del \- delete a file or a directory in your shellm bin/lib directory
.SH "SYNOPSIS"
.br
\fBshellm-del\fR shellm\fB\-del\fR [\fB\-p\fR] \fIFILE\fR|\fIDIR\fR
.SH "OPTIONS"
.IP "\fB-p\fR,\fB --purge\fR" 4
Also delete the data directory in shellm data
.IP "\fB-h\fR,\fB --help\fR" 4
Prints this help and exit
